### ISSUE TITLE
Makefile.include:378: recipe for target 'build/z1/obj/atom.o' failed

### ISSUE THREAD

**Issue by AnthonyGuz** [mbaddeley/usdn-ng#3]
Somebody could help me please. when I use `make clean & make` in controller folder, appear this error.
![image](https://user-images.githubusercontent.com/22897424/114590360-4a212380-9c4e-11eb-871c-d07e32e55e54.png)
I don't know what is the problem.

**Comment by mbaddeley** [comment]
Hi Anthony,

What's the command you are using? i.e. what are you typing into the
terminal?

Michael

**Comment by AnthonyGuz** [comment]
I'm using `make TARGET=z1` into _usdn/examples/sdn/controller_ folder

anthony@ubuntu:~/usdn-ng/examples/sdn/controller$ make TARGET=z1
  MKDIR     build/z1/obj
  CC        ../../../os/contiki-main.c
  CC        ../../../arch/platform/z1/./contiki-z1-platform.c
  CC        ../../../os/dev/leds.c
  CC        ../../../arch/platform/z1/dev/xmem.c
  CC        ../../../arch/platform/z1/dev/i2cmaster.c
  CC        ../../../arch/cpu/msp430/f2xxx/spi-legacy.c
  CC        ../../../arch/dev/radio/cc2420/cc2420.c
  CC        ../../../arch/platform/z1/dev/cc2420-arch.c
  CC        ../../../arch/cpu/msp430/./cc2420-arch-sfd.c
  CC        ../../../arch/platform/z1/./node-id-z1.c
  CC        ../../../os/lib/sensors.c
  CC        ../../../arch/platform/z1/dev/button-sensor.c
  CC        ../../../os/storage/cfs/cfs-coffee.c
  CC        ../../../arch/cpu/msp430/f2xxx/uart0.c
  CC        ../../../arch/cpu/msp430/dev/uart0-putchar.c
  CC        ../../../arch/cpu/msp430/./uip-ipchksum.c
  CC        ../../../os/dev/slip.c
  CC        ../../../arch/cpu/msp430/./slip_uart0.c
  CC        ../../../arch/platform/z1/dev/z1-sensors.c
  CC        ../../../arch/platform/z1/dev/adxl345.c
  CC        ../../../arch/platform/z1/dev/temperature-sensor.c
  CC        ../../../arch/platform/z1/dev/z1-phidgets.c
  CC        ../../../arch/platform/z1/dev/light-sensor.c
  CC        ../../../arch/platform/z1/dev/battery-sensor.c
  CC        ../../../arch/platform/z1/dev/sky-sensors.c
  CC        ../../../arch/platform/z1/dev/tmp102.c
  CC        ../../../arch/platform/z1/./platform.c
  CC        ../../../arch/cpu/msp430/f2xxx/msp430.c
  CC        ../../../arch/cpu/msp430/./flash.c
  CC        ../../../arch/cpu/msp430/f1xxx/clock.c
  CC        ../../../arch/cpu/msp430/./leds-arch.c
  CC        ../../../arch/cpu/msp430/./watchdog.c
  CC        ../../../arch/cpu/msp430/./lpm.c
  CC        ../../../arch/cpu/msp430/f1xxx/rtimer-arch.c
  CC        ../../../arch/cpu/msp430/./int-master.c
  CC        ../../../os/lib/crc16.c
  CC        ../../../os/services/atom/atom-net.c
  CC        ../../../os/services/atom/atom-buffer.c
  CC        ../../../os/services/atom/atom.c
../../../os/services/atom/atom.c: In function ‘atom_run’:
../../../os/services/atom/atom.c:260:7: error: ‘app’ may be used uninitialized in this function [-Werror=uninitialized]
../../../os/services/atom/atom.c: At top level:
cc1: error: unrecognized command line option "-Wno-unused-const-variable" [-Werror]
cc1: all warnings being treated as errors
../../../Makefile.include:378: recipe for target 'build/z1/obj/atom.o' failed
make: *** [build/z1/obj/atom.o] Error 1

**Comment by mbaddeley** [comment]
I believe this issue should be fixed if following the latest README instructions. Closing.
