### ISSUE TITLE
Rerouting node/Forcing topology

### ISSUE THREAD

**Issue by BerkAyaz** [mbaddeley/usdn-ng#6]
Hi,

I read in your paper that you could reroute nodes and that this could be done with the controller.
How can I do this, is this done automatically via the controller or is there some kind of command I can specify with the Contiki shell (or something else) ?

Is there a way to force a certain topology, e.g. force DAG root node A to have 1 child node B and node B having 1 child node C. (so making sure that node C does not become the child node of DAG root node A)

**Comment by mbaddeley** [comment]
No command unfortunately, you would need to create a controller application to allow you to set routes that way. Currently routes are set using RPL source routing, or using Shortest Path routing.
